### example local orderSave
POST http://localhost:8189/hello
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/hi?name=Tom
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/post/hi?name=Tom
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/shenyu/client/hello
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/shenyu/client/hi?name=Tom
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/shenyu/client/post/hi?name=Tom
Accept: application/json
Content-Type: application/json

### example local orderSave
POST http://localhost:8189/order/save
Accept: application/json
Content-Type: application/json

{
  "id": 123,
  "name": "order"
}
### example local orderSave
GET http://localhost:8189/order/findById?id=123
Accept: application/json
Content-Type: application/json

### example local path
GET http://localhost:8189/order/path/123/hahah
Accept: application/json
Content-Type: application/json

### example local path
GET http://localhost:8189/order/path/123/name
Accept: application/json
Content-Type: application/json

### example local oauth2
GET http://localhost:8189/order/oauth2/test
Accept: application/json
Content-Type: application/json
Authorization:AuthorizationContext

### example local payment
POST http://localhost:8189/test/payment
Accept: application/json
Content-Type: application/json

{
  "userId": 123,
  "userName": "name"
}

### example local findByUserId
GET http://localhost:8189/test/findByUserId?userId=123
Accept: application/json
Content-Type: application/json

### example local findByUserId
GET http://localhost:8189/test/findByUserId?userId=123%5D%2D
Accept: application/json
Content-Type: application/json

### example local findByUserId
GET http://localhost:8189/test/findByUserId?userId=123%5D%2D%2Casd
Accept: application/json
Content-Type: application/json

### example local findByUserId
GET http://localhost:8189/test/findByUserId?userId=123%5D%2D,asd
Accept: application/json
Content-Type: application/json

### example local path
GET http://localhost:8189/test/path/123?name=haha
Accept: application/json
Content-Type: application/json

### example local path
GET http://localhost:8189/test/path/123/name
Accept: application/json
Content-Type: application/json

### example local waf pass
POST http://localhost:8189/test/waf/pass
Accept: application/json
Content-Type: application/json

### example local waf deny
POST http://localhost:8189/test/waf/deny
Accept: application/json
Content-Type: application/json

### example local request parameter pass
GET http://localhost:8189/test/request/parameter/pass?requestParameter=test
Accept: application/json
Content-Type: application/json

###