server:
  port: 8074

spring:
  application:
    name: consul-provider-service
  cloud:
    consul:
      host: 192.168.236.133
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 表示注册时使用IP而不是hostname 不写这个配置，在docker下的consul里面健康检查会失败
        prefer-ip-address: true
        # 注册服务所在端口
        port: ${server.port}
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:192.168.40.1:${server.port}